### PR TITLE
Added ability to create a Triangulation with only points and triangles as input

### PR DESCRIPTION
**Pull request by matgrand**
In case someone already has an unconstrained triangulation in the form of points and triangles, but no boundary, I added a constructor for exactly that. It's basically calling the previous method with boundary_nodes = [nothing].

### CODE REVIEW

**Comment by DanielVandH** [comment]
Thanks! Does this actually work? You'll need to add some tests. I assumed that this would run into errors - a better default is probably `IntegerType[]` instead of `[nothing]`.

One issue with this method, and why I haven't got around to implementing it yet, is that the triangulation will not work in a lot of cases without the proper boundary information. For the unconstrained triangulation case, this boundary is of course the convex hull, but this constructor doesn't know that. I think there are two possible resolutions
- Document that the constructor is only valid for unconstrained triangulations, and pass `boundary_nodes = get_vertices(convex_hull(points))`. This approach will also not work if there are some points in `points` that are not vertices in `triangles` though - maybe just documenting that limitation is useful, or use the approach below to find the convex hull (from the boundary) and sort it using `sort_convex_polygon!`.
- Allow for any boundary to be provided, and reconstruct it from the triangles. That is, you can loop over `each_triangle(tri)` and check if any of the edges have no adjacent edge (so you'd need to construct the `Adjacent` map and use `edge_exists(get_adjacent(adj, i, j))`). Those without an adjacent edge form the boundary. This is a bit hard though since it requires sorting the boundaries and, since the boundaries may be disconnected, knowing how to separate different chains of line segments. 

The first approach is probably sufficient for now. What do you think?

**Comment by matgrand** [comment]
I will try the first approach. 
I'give you a little bit more context: my issue (but maybe it's fairly common) is that I already have a triangle mesh from other software (in the form of points + triangles) and I simply want to "import" it to do stuff on it. In my code I did it with Triangulation(points, triangles, [nothing]) and it works correctly. But I thought a constructor with only points and triangles was needed. 
I understand the problems and the underlying logic of the issue you highlighted, and I will address it as you suggested (first approach). 
Maybe in the future a function to import a triangle mesh would be useful, that automatically checks the validity of the triangulation before converting. But I think the convex hull will suffice in most cases.

**Comment by DanielVandH** [comment]
Thanks! I will take a closer look soon.

In v2.0 I intend on creating a separate unconstrained triangulation type so that cases like this are much easier to handle, I imagine that would be helpful for your use case. What software are you converting from btw? I also wanted to at some point allow for converting a mesh from Shewchuks Triangle but never got around it.

**Comment by matgrand** [comment]
I'm reading a .mat file, with the 2 vectors: points and triangles, they were probably generated using some version of Delaunay triangulation in matlab but I'm not sure.

**Comment by DanielVandH** [comment]
In addition to fixing the failed test (where 'tri' is undefined in your test), can you also bump the version to v1.5 and add a statement to news please? Thanks!

**Comment by matgrand** [comment]
It should be done, sorry, I'm new to Julia and haven't done many PRs either

**Comment by DanielVandH** [comment]
Not a problem at all, I very much appreciate the contribution! Any final edits that are needed I'll make and merge soon, thanks!

**Comment by DanielVandH** [comment]
I changed a few things:

- Clarified the news statement that its about reconstructing from the points/triangles.
- Bumped the version to 1.5.
- I now technically allow ghost triangles but they are skipped (the test was failing as written, so this addresses that).
- To make sure the returned triangulation is actually unconstrained, I remove the convex hull boundary from `tri` using `unlock_convex_hull!`.
- Moved the test into a different file.

Once the CI passes should be go I think. Thanks!

**Comment by DanielVandH** [comment]
Now available and registered in v1.5.0. Thanks for the contribution :)

**Pull request merged**
